# Generated by Django 4.0.2 on 2022-03-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_historicaluser_image_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='image',
            field=models.TextField(blank=True, default='profiles/generic/profile_whats.jpg', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='profiles/generic/profile_whats.jpg', max_length=255, null=True, upload_to='profiles/'),
        ),
    ]
