# Generated by Django 4.0.2 on 2022-05-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuario_huella'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='huella',
            field=models.CharField(max_length=9999999, unique=True, verbose_name='Huella'),
        ),
    ]
