# Generated by Django 4.0.2 on 2022-05-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_usuario_huella'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='huella',
            field=models.ImageField(max_length=10485760, unique=True, upload_to='huellas/', verbose_name='Huella'),
        ),
    ]
