# Generated by Django 4.0.2 on 2022-05-01 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_cita_updated_by_alter_consulta_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='expediente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.expediente', verbose_name='Expediente'),
            preserve_default=False,
        ),
    ]
