# Generated by Django 4.0.2 on 2022-05-02 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_paciente_sexo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen',
            old_name='comentarios_imagen',
            new_name='comentariosImagen',
        ),
    ]
