# Generated by Django 4.0.2 on 2022-05-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_paciente_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='curp',
            field=models.CharField(max_length=18, verbose_name='CURP'),
        ),
    ]
