# Generated by Django 4.0.2 on 2022-05-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cita_options_alter_consulta_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='huella',
            field=models.CharField(max_length=999999, unique=True, verbose_name='Huella'),
        ),
    ]
