# Generated by Django 4.0.2 on 2022-05-01 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_usuario_huella'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='object_id',
        ),
        migrations.AddField(
            model_name='consulta',
            name='cita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.cita', verbose_name='Cita'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagen',
            name='cita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.cita', verbose_name='Cita'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='cita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.cita', verbose_name='Cita'),
            preserve_default=False,
        ),
    ]
