# Generated by Django 4.0.2 on 2022-05-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_cita_content_type_remove_cita_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='huella',
            field=models.ImageField(max_length=10485760, upload_to='huellas/', verbose_name='Huella'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='huella',
            field=models.ImageField(max_length=10485760, upload_to='huellas/', verbose_name='Huella'),
        ),
    ]
