# Generated by Django 4.0.2 on 2022-05-02 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_comentarios_imagen_imagen_comentariosimagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen',
            old_name='comentariosImagen',
            new_name='comentarios_imagen',
        ),
    ]
