# Generated by Django 4.0.2 on 2022-05-02 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_comentariosimagen_imagen_comentarios_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cita', related_query_name='citas', to='core.cita', verbose_name='Cita'),
        ),
    ]
