# Generated by Django 4.0.2 on 2022-05-02 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_consulta_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta', related_query_name='consultas', to='core.cita', verbose_name='Cita'),
        ),
    ]
