# Generated by Django 4.0.2 on 2022-03-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_image_historicaluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='image',
            field=models.TextField(blank=True, default='profiles/generic/profile_kakashi.jpg', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='profiles/generic/profile_kakashi.jpg', max_length=255, null=True, upload_to='profiles/'),
        ),
    ]
